### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by iSarCasm**
Ruby **1.9.3** -> Ruby **2.2.2** (the most stable and supported version currently)
ActiveSupport **3.2** -> ActiveSupport **5.1**
nokogiri **1.6** -> nokogiri **1.8**
mail **2.5** -> mail **2.7**

**All specs are green (104 examples)** _(travis shows red because of outdated ruby jobs 1.9, 2, 2.1)_

### CODE REVIEW

**Comment by dguido** [comment]
Oh I see. You can trim the travis.yml to include only current Ruby versions!

**Comment by iSarCasm** [comment]
@dguido For some reason fails for `jruby-head`. Probably have to investigate this.

**Comment by dguido** [comment]
I think you can trim the travis.yml even further. Let's drop 2.2.x, rbx, and jruby-19mode. This is an excessive amount of testing for such a simple app.

**Comment by iSarCasm** [comment]
@dguido dropped them. Changed `jruby-head` to `jruby-9.1.9`

**Pull request merged**
